name: DevOps Capstone Project CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

defaults:
 run:
  working-directory: ./capstone_project/hello-world

jobs:

  build:

    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: ./capstone_project/hello-world
    - name: npm install
      run: npm ci
    - name: npm build
      run: npm run build --if-present
    - name: npm test
      run: npm test
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag helloworld:$(date +%s)
